### PR TITLE
Disable Panel View for kindle scribe

### LINKED ISSUE #498: Disable 4 corner panels?
Is there a way to avoid zooming in on the corners of pages? Accidentally zooming in happens a lot when turning pages. Kindle Scribe is big so I don't need to zoom. 

In Amazon purchased books (example Demon Slayer vol 1), I can disable virtual panel to do this.

### PR DESCRIPTION
**Pull request by darodi**
Disable Panel View for kindle scribe

- fix #498

### CODE REVIEW

**Comment by axu2** [comment]
I actually suggest reverting this, it seems to autocrop the white space when viewed on device. I'd prefer keeping the whitespace.

**Comment by darodi** [comment]
@axu2 

Even with crop disabled?
We should maybe make "disable panel view" a checkbox.

**Comment by axu2** [comment]
Yea, even though the files aren't cropped in the EPUB and when viewing the final MOBI in the Kindle PC app, they end up cropped when viewed on the actual Kindle. Very strange behavior. Thanks for reverting.

**Comment by jaroslawjanas** [comment]
> @axu2
> 
> Even with crop disabled? We should maybe make "disable panel view" a checkbox.

Any plans for doing this?
Personally, I don't use PV and it gets in the way, so I would very much welcome such an option.

**Comment by axu2** [comment]
@jaroslawjanas Should be fixed in #899, please use the linked test build. It disables panel view

**Pull request merged**
