### PR TITLE
fix dark mode by removing background image temporarily

### PR DESCRIPTION
**Pull request by axu2**
Temporarily removing background image. This fixes the black text on dark mode issue on macOS.

image
image

@ctrleo I'm sorry, but I made several GUI commits recently so you'll need to resume from this base point, merge conflicts are guarenteed so may be easier to just start a new PR.

- #793 related

### CODE REVIEW

**Comment by jeffmcneill** [comment]
@axu2 Thanks for this, and also @ctrleo for your many efforts. I can't test as is, but if an AppImage is made available, I'll be able to.

**Comment by axu2** [comment]
@jeffmcneill test builds here https://github.com/ciromattia/kcc/releases/tag/v7.1.0

**Comment by jeffmcneill** [comment]
Got an error on runtime:

~~~
[PYI-28662:ERROR] Failed to load Python shared library '/tmp/_MEIe7t95C/libpython3.11.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by /tmp/_MEIe7t95C/libpython3.11.so.1.0)
~~~

**Comment by axu2** [comment]
@jeffmcneill What are you running? This was built on ubuntu-22.04

**Comment by jeffmcneill** [comment]
Debian stable

```
    ,g$$$$$$$$$$$$$$$P.       -------- 
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 12 (bookworm) x86_64 
 ,$$P'              `$$$.     Host: NUC8i3BEH J72753-306 
',$$P       ,ggs.     `$$b:   Kernel: 6.11.10+bpo-amd64 
`d$$'     ,$P"'   .    $$$    Uptime: 22 hours, 31 mins 
 $$P      d$'     ,    $$P    Packages: 2208 (dpkg) 
 $$:      $$.   -    ,d$$'    Shell: bash 5.2.15 
 $$;      Y$b._   _,d$P'      Resolution: 1920x1080, 1920x1080 
 Y$$.    `.`"Y$$$$P"'         DE: Xfce 4.18 
 `$$b      "-.__              WM: Xfwm4 
  `Y$$                        WM Theme: Default 
   `Y$$.                      Theme: Adwaita-dark [GTK2/3] 
     `$$b.                    Icons: gnome [GTK2/3] 
       `Y$$b.                 Terminal: xfce4-terminal 
          `"Y$b._             Terminal Font: Monospace 12 
              `"""            CPU: Intel i3-8109U (4) @ 3.600GHz 
                              GPU: Intel CoffeeLake-U GT3e [Iris Plus Graphics 655] 
                              Memory: 3301MiB / 15858MiB 
```

**Comment by jeffmcneill** [comment]
Also:

- ldd --version:  ldd (Debian GLIBC 2.36-9+deb12u9) 2.36
- python3 --version:  Python 3.11.2

**Comment by axu2** [comment]
@shaicoleman do you have any insight?

**Comment by shaicoleman** [comment]
The AppImage should probably include glibc to work better across distros.
The revert changed it to `ubuntu-latest`. Maybe `ubuntu-22.04` would work better.
That said, I'm currently using the flatpak version, as v6 does everything I need.

**Comment by axu2** [comment]
@shaicoleman Currently, `ubuntu-latest` refers to 22.04. https://github.com/actions/runner-images?tab=readme-ov-file#available-images

Do you think adding `glibc` to this line would fix the issue?
https://github.com/ciromattia/kcc/blob/2189f4b1cb6e939d70e6e6063ff7fbbd3f668079/.github/workflows/package-linux.yml#L37

Feel free to fork KCC, enable GitHub Actions on your fork, and run the linux action to build and download an appimage from GitHub servers. @jeffmcneill

**Comment by axu2** [comment]
@jeffmcneill @shaicoleman 7.1.1 is now on flat hub.

**Comment by shaicoleman** [comment]
@axu2 , thanks, the flatpak works well for me

**Comment by jeffmcneill** [comment]
@axu2 I don't use flatpaks, so I'll stick with the non-dark mode release until the appimage works again.

**Comment by axu2** [comment]
> @axu2 , The AppImage should probably include glibc to work better across distros. The revert changed it to `ubuntu-latest`. Maybe `ubuntu-22.04` would work better. That said, I'm currently using the flatpak version, as v6 does everything I need.

> @shaicoleman Currently, ubuntu-latest refers to 22.04. https://github.com/actions/runner-images?tab=readme-ov-file#available-images

@shaicoleman Turns out I was wrong. The docs say `ubuntu-latest` refers to 22.04 but the actual logs sometimes were building it on 24.04. That was the problem.

**Comment by jeffmcneill** [comment]
@axu2 @shaicoleman Latest 7.1.2 AppImage works a charm! Thanks for hunting down that bug. I had a hunch we could blame Microsoft for the failure... -_-

**Pull request merged**
