### PR TITLE
replace exit() with sys.exit()

### LINKED ISSUE #588: Exit error
I ran into this error message after I tried opening kcc version 5.6.3.

I use windows 10 and the issue is not my antivirus-software, because I already tried downloading and opening it with the software disabled.

I also tried the non-docker version but it still didn't work.

image

### PR DESCRIPTION
**Pull request by axu2**
Fixes #588 @DemonEye888

Temporary EXE here: https://github.com/axu2/kcc/actions/runs/6125895319

Please test to confirm it works.

### CODE REVIEW

**Comment by darodi** [comment]
isn't `import sys` needed?

**Comment by axu2** [comment]
@darodi added and force pushed. It's already imported in most files though.

**Comment by axu2** [comment]
Mind finalizing v5.6.3 as is so we don't get questions in the future from people who initially downloaded v5.6.2 since it shows up first like in #591 v5.6.3 has proved pretty stable so far.

image

However, don't include this PR in it. I finally managed to replicate this.

Fixing this issue now makes the app exit silently instead of throwing an error 😓 

I placed KCC in the KP3 directory.

**Comment by DemonEye888** [comment]
I can only test it at the end of next week because I am not at home right now.
But I will when I get the chance.
Thanks again for the help!

**Comment by darodi** [comment]
> @darodi Mind finalizing v5.6.3 

@axu2 
done

**Pull request merged**
