### PR TITLE
refactor display when kindlegen is missing

### PR DESCRIPTION
**Pull request by darodi**
refactor display when kindlegen is missing
display_kindlegen_missing

- fixing links
- same display called in 2 contexts

### CODE REVIEW

**Comment by darodi** [comment]
- fix #491

**Comment by axu2** [comment]
I tried running this from source on Mac.

Just brew installing the cask is not enough. You also need to copy kindle gen to /usr/bin/local, like the wiki says.

I recommend we delete the OS specific code and just link directly to the wiki, similar to how we do for 7z.

https://github.com/ciromattia/kcc/wiki/Installation#kindlegen

**Comment by axu2** [comment]
In retrospect, it was probably because only Kindle Previewer was added to PATH in the KCC code and not comic creator...

**Comment by axu2** [comment]
Superseded by #566 due to merge conflicts

**Pull request merged**
