### PR TITLE
fix update detection by using requests library over urllib

### PR DESCRIPTION
**Pull request by axu2**
The update utility stopped working for me until i changed this.

Was getting this error

```python
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)>
```

- related #518

### CODE REVIEW

**Comment by axu2** [comment]
@catsout I'll put out a formal release once you add requests to the flatpak.

**Comment by catsout** [comment]
@axu2 Better to add this requirement to setup.py.

**Comment by axu2** [comment]
Done 
- https://github.com/ciromattia/kcc/commit/7eb985337c87629325dd240bbb6e8321c2aa86e4

**Comment by winstonma** [comment]
@axu2 Not sure if it is related but the latest flatpak version doesn't work. Thanks for checking

```bash
$ flatpak run io.github.ciromattia.kcc
Traceback (most recent call last):
  File "/app/bin/kcc", line 33, in <module>
    sys.exit(load_entry_point('KindleComicConverter==5.6.5', 'gui_scripts', 'kcc')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/kindlecomicconverter/startup.py", line 29, in start
    from . import KCC_gui
  File "/app/lib/python3.11/site-packages/kindlecomicconverter/KCC_gui.py", line 28, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Comment by catsout** [comment]
Seems with --root arg，python setup.py will not check dependencies.  
I already added this requirement, wait for flathub's update.

**Pull request merged**
