### PR TITLE
Update shared.py

### PR DESCRIPTION
**Pull request by ndtoan96**
Fix version of slugify

### CODE REVIEW

**Comment by ndtoan96** [comment]
Sorry, now I checked again it seems slugify change version structure recently (from v6). It's weird because I install KCC via PyPi and got error at that line, which means PyPi installs the latest version of slugify instead of respecting the dependency mentioned in requirements.txt.

**Comment by darodi** [comment]
@ndtoan96 
Does the new slugify version work fine?


> Sorry, now I checked again it seems slugify change version structure recently (from v6). It's weird because I install KCC via PyPi and got error at that line, which means PyPi installs the latest version of slugify instead of respecting the dependency mentioned in requirements.txt.

I found the problem. [kcc/setup.py](https://github.com/ciromattia/kcc/blob/4ec4c9966c727d6dac44507d34607bd7d2c5ed5c/setup.py#L84) doesn't include the [requirements.txt](https://github.com/ciromattia/kcc/blob/master/requirements.txt) and there is a mismatch. 
PyPi version was built using [kcc/setup.py](https://github.com/ciromattia/kcc/blob/4ec4c9966c727d6dac44507d34607bd7d2c5ed5c/setup.py#L84).

https://github.com/ciromattia/kcc/blob/4ec4c9966c727d6dac44507d34607bd7d2c5ed5c/requirements.txt#L4

https://github.com/ciromattia/kcc/blob/4ec4c9966c727d6dac44507d34607bd7d2c5ed5c/setup.py#L84




something like this would be better in [kcc/setup.py](https://github.com/ciromattia/kcc/blob/master/setup.py) 

```python
with open("requirements.txt", "r", "utf-8") as f:
    requires = f.readlines()

setuptools.setup(
...

    install_requires=requires,
```

**Comment by ndtoan96** [comment]
@darodi 
> Does the new slugify version work fine?
Not sure, I got plenty problem with images processing part, the binary works fine though. Will look at it when I have time, maybe due to dependencies just like this one.

**Comment by darodi** [comment]
Duplicate of #411 
Duplicate of #410

**Pull request closed without merging**
