### PR TITLE
A better page number-crop algorithm. (Manga)

### PR DESCRIPTION
**Pull request by neyney10**
## Summary
1. I wrote a new method to crop pages, as the current one fails.
2. Attached some cool gifs.

## Motivation
E-reader screen real estate is an important resource.
More available screen size means more details can be better seen, especially text.
Text is one of the most important elements that need to be clearly readable on e-readers,
which mostly are smaller devices where the need to zoom is unwanted.

By cropping the page number on the bottom of the page, 2%-5% of the page height can be regained
that allows us to upscale the image even more.
- Most of the time the screen height is the limiting factor in upscaling, rather than its width.

## The Current Algorithm Fails
While it is possible to adjust the 'power' of the cropping, I can only gain some success when the power is at least 4 (using the power user EXE), where the GUI itself only allows up to 2.

The current algorithm fails in all of the cases that I have at hand.
- I also don't want to crop the page number In case it would crop some manga-content.  Some high power levels cropped some of my pages too much.
- But I allow some level of cropping to achieve a tighter bounding box around the main manga-content with higher power levels.

## A Better Algorithm
I wrote a Python function using PIL, NumPy (openCV might perform faster, but I regressed to PIL as it exists as a dependency already and including OpenCV is heavy, package weight-wise).

<details>
  <summary> OUTPUT EXAMPLES OF THE NEW ALGORITHM </summary>

**(I extended the power level limit to 3, from the previous limit of 2)**

###  Page Number Cropping

ex1h001
ex5ga002

### Showcasing Its Ability To Retain Manga Content
**It does not crop the page number if it detects other things that might be cropped along with the page number.**

ex8n003
ex2h010
ex3b001
ex4bl001
ex6h006
ex7h009

</details>

## Issues
- My new algorithm uses the 'power' parameter differently than the other algorithm that simply crops the margins without the page number. A 'power level' in "Crop margins"  is different than a 'power level' in "Crop margins & page numbers". This might lead to inconsistent expectations from the user and confuse them.

### CODE REVIEW

**Comment by axu2** [comment]
Wow this looks incredible, might take me a while to fully review it though. 

For reference, my perspective is mostly using a Kindle Scribe 10" which doesn't need to zoom. But when I use smaller devices cropping is essential. 

Have you looked into any android manga reading software? I bet they might like a feature like this, and maybe they have something similar. 

And what platform did you develop on? I use macOS (apple silicon).

**Comment by neyney10** [comment]
> Wow this looks incredible, might take me a while to fully review it though.
> For reference, my perspective is mostly using a Kindle  Scribe 10" which doesn't need to zoom or crop at all. But when I use  smaller devices like an android Hisense a9 eink phone cropping is  essential.

I hope it would actually work for others, I tested it on 30+ images from 5-6 different Mangas. I want to try it on some more Mangas before I'll continue.

> Have you looked into any android manga reading software? I bet they might like a feature like this, and maybe they have something  similar.

Very shallowly. I tried to search on Google for some existing manga or comic crop algorithms, even some general manga-readers apps, But couldn't find something meaningful (aside of the standard cropping). I usually read on my PC or my [used to have] first gen Kindle Paperwhite 6" (as you can understand my constraint here). 

Recently, my Kindle's screen shattered and I've ordered a new e-reader with a 7.8" screen. I've yet to receive it so in the meantime I thought I would at least try to optimize the Mangas that I plan to read/load when I get it. Hence, I tried to write this algorithm.


> And what platform did you develop on? I use macOS (arm64/apple silicon).

I use an old Windows 10 laptop (intel x86-64)

> And do you you have a general idea of the performance difference and how much increases the binary size? Aka
> ’python setup.py build_binary’

TBH, I forgot to measure the binary, so I ran it just now to see.
It does increase the EXE file considerably by 20 MB~ (a 30% increase) to 68 MB up from 48.3 MB. The only package that I've added is NumPy. I'll see how I can optimize it. In the worst case, I can re-implement it in basic Python math, with probably some performance hit, although I didn't use anything complicated that necessitates NumPy.

Regarding performance, to my surprise, it didn't suffer much of a hit, I did multiple types of benchmarks.
- On my PC the algorithm alone takes roughly 0.15 sec per image (when running it outside of KCC).
- Compared to the existing "crop margins" which is similar to the existing "crop margins & page numbers", on 10 chapters of 'Blame!' (300MB, 440~ Images) takes a similar time on my machine: 6 minutes from clicking "start" to the time I get the output file. Hence I assume that the processing here of the algorithm is negligible compared to all the other stuff that happening (Open file, extract, read image, upscale, rotate, convert, build book...).

By the way,
I found a small bug in one of my functions, I'll upload a fix soon. 
I think I might want to postpone the pull request a bit until I try it a bit more on other types of Mangas.

**Comment by neyney10** [comment]
While I agree, I thought we wanted to optimize output file size (as numpy increases it by 30%).
Regardless, I only used trivial functions of NumPy and upon first inspection, the performance of the non-numpy replacement methods are on par (and sometimes faster in my quite shallow tests).

Do you want me to add the NumPy version back?

Unrelated - I've detected that the algorithm sometimes fails on thin fonts and single-digit page numbers. Also, there is an issue with using higher power levels that causes the page number to become distorted and the algorithm fails to detect it (currently I'm optimizing power=1 to work the best in most cases).

**Comment by neyney10** [comment]
> That's great! Excuse me, is the Cropping mode value Cropping Power: 2 in KCC's current version of the cropping mode that corresponds to the Power3 you're demonstrating?

Hi! No, the power levels [0...3] that I'm using are different entirely from the current power levels of [0...2] that exist currently in KCC v6.1.0.

I've noted that in the issues at the bottom of OP.

> My new algorithm uses the 'power' parameter differently than the other algorithm that simply crops the margins without the page number. A 'power level' in "Crop margins" is different than a 'power level' in "Crop margins & page numbers". This might lead to inconsistent expectations from the user and confuse them.

**Comment by zhaohengkang** [comment]
> > 真棒！请问，在 KCC 当前版本的裁剪模式中，裁剪模式值 Cropping Power： 2 是否对应于您正在演示的 Power3？
> 
> 你好！不，我使用的功率级别 [0...3] 与当前存在于 KCC v6.1.0 中的 [0...2] 的当前功率级别完全不同。
> 
> 我在 OP 底部的问题中注意到了这一点。
> 
> > 我的新算法使用“power”参数的方式与其他算法不同，后者只是裁剪边距而不裁剪页码。“裁剪边距”中的“功效级别”与“裁剪边距和页码”中的“功效级别”不同。这可能会导致用户的期望不一致，并使他们感到困惑。

Okay, so how do I use the algorithm you provided? I felt it was fantastic, just what I needed. Or, can you help provide an exe file that supports this algorithm?

**Comment by zhaohengkang** [comment]
> > That's great! Excuse me, is the Cropping mode value Cropping Power: 2 in KCC's current version of the cropping mode that corresponds to the Power3 you're demonstrating?
> 
> Hi! No, the power levels [0...3] that I'm using are different entirely from the current power levels of [0...2] that exist currently in KCC v6.1.0.
> 
> I've noted that in the issues at the bottom of OP.
> 
> > My new algorithm uses the 'power' parameter differently than the other algorithm that simply crops the margins without the page number. A 'power level' in "Crop margins" is different than a 'power level' in "Crop margins & page numbers". This might lead to inconsistent expectations from the user and confuse them.

Okay, so how do I use the algorithm you provided? I felt it was fantastic, just what I needed. Or, can you help provide an exe file that supports this algorithm?

**Comment by zhaohengkang** [comment]
> > That's great! Excuse me, is the Cropping mode value Cropping Power: 2 in KCC's current version of the cropping mode that corresponds to the Power3 you're demonstrating?
> 
> Hi! No, the power levels [0...3] that I'm using are different entirely from the current power levels of [0...2] that exist currently in KCC v6.1.0.
> 
> I've noted that in the issues at the bottom of OP.
> 
> > My new algorithm uses the 'power' parameter differently than the other algorithm that simply crops the margins without the page number. A 'power level' in "Crop margins" is different than a 'power level' in "Crop margins & page numbers". This might lead to inconsistent expectations from the user and confuse them.

Ok, so how should I use the algorithm you provided in KCC? I felt it was fantastic, just what I needed. Or, can you help me provide a KCCexe file that supports this algorithm?

**Comment by axu2** [comment]
@neyney10 Enable GitHub Actions on your fork. Then create a release on your fork, which triggers GitHub actions to create binaries for all supported platforms, like here" https://github.com/axu2/kcc/releases

Also, feel free to build a numpy version so we can more easily see the size difference.

**Comment by zhaohengkang** [comment]
I have used the better optimization algorithm you provided and it is really great! Thank you very much!

**Comment by zhaohengkang** [comment]
> 在分支上启用 GitHub Actions。然后在你的分支上创建一个发布，这会触发 GitHub 操作为所有支持的平台创建二进制文件，就像这里 https://github.com/axu2/kcc/releases 一样。
> 
> 此外，请随意构建一个 numpy 版本，以便我们可以更轻松地查看跨平台的大小差异。

I did it. Thank you

**Comment by axu2** [comment]
@zhaohengkang feel free to upload some comparison photos.

**Comment by zhaohengkang** [comment]
> 随意上传一些比较照片。

The following is the mobi file generated by importing pdf files to KCC, you can see that the original algorithm can only extract pictures and not crop, and a better algorithm can also crop it.

**Comment by zhaohengkang** [comment]
> 随意上传一些比较照片。

Here are the mobi files generated by the import folder, and these are the comparison graphs.

**Comment by axu2** [comment]
Made some test builds and size comparison:

https://github.com/axu2/kcc/releases

image

**Comment by neyney10** [comment]
> Made some test builds and size comparison:
> 
> https://github.com/axu2/kcc/releases
> 
> image

Yes, I reached the same numbers.

How do you want to continue?

**Comment by axu2** [comment]
I think the size difference of the final distributable files is negligible, I'd rather keep numpy. I've done lots of image processing work in the past with numpy and know how useful it is.

Also, which do you envision?

1) replacing current crop functionality entirely?
2) using yours as the new default and calling the old one "legacy"
3) using yours as an "experimental" option?

**Comment by neyney10** [comment]
> I think the size difference of the final distributable files is negligible, I'd rather keep numpy. I've done lots of image processing work in the past with numpy and know how useful it is, it may come in handy in the future.
> 
> I also tested startup times and didn't see any significant difference. (maybe 1 second?)

I see. Then NumPy version it is.

Regarding the algorithm - there are still issues with thin fonts of page numbers and instances of a single-digit page num that the algorithm fails to detect with higher power levels (but less of a problem with lower power levels).

As Zhao demonstrated, the algorithm works fine in most cases and I think it is ready for general use, even if more tweaks and improvements are needed for some edge cases or maybe some scenarios that I haven't tested yet.

What about the issue I have with the inconsistency with power levels of the current "crop margins" versus the new "crop margin + page num"?
Should we modify the existing "crop margins" algorithm to make it consistent?

--------------------
@zhaohengkang Very nice comparison images you compiled there! seems like you worked hard sharing these results!
I was wondering if you tried running the algorithm with power=1, as it seems you only shared comparisons with higher power levels such as 2 and 3. I assume that lower power levels are too weak to crop the watermark?

**Comment by zhaohengkang** [comment]
@neyney10   Sorry, because when I turned it on, the default was power=2, and precisely this power met my requirements, so I did not use the lower power to test.

**Comment by axu2** [comment]
> What about the issue I have with the inconsistency with power levels of the current "crop margins" versus the new "crop margin + page num"?
Should we modify the existing "crop margins" algorithm to make it consistent?

Sorry, totally forgot you asked a question here. Maybe the best option is to introduce another checkbox called LEGACY or experimental crop so users can revert to prior behavior depending on which makes more sense to be the default. And be sure to put a note in the tooltip hover that says that the power usage is different.

**Comment by keruiter** [comment]
tmp3EFE
tmp14F4
image

Hi, thank you for providing such an amazing algorithm! However, I encountered an issue while using it: when I select the Cropping mode (i.e., when it is "checked"), an error often occurs. A screenshot of the error is attached. It seems that the issue might be related to the algorithm's inability to handle blank images within comic files.

To be honest, I’m not very familiar with the technical aspects, so I’ve been testing things out bit by bit. Initially, I suspected that the problem was due to the format conversion software I was using, so I tried several different ones, but the error persisted. Then, I thought it might be related to the PDF format, so I converted it to a folder containing image files and tested again, but the issue remained. Eventually, I discovered that the problem occurs when there are completely blank images within the comic files.

I further tested and found that the error only happens when the Cropping mode is checked. When it’s set to "indeterminate" or when cropping is not used, everything works fine. Additionally, using the original cropping algorithm version of KCC does not have this issue.

**Comment by neyney10** [comment]
> tmp3EFE
> tmp14F4
> image
> 
> Hi, thank you for providing such an amazing algorithm! However, I encountered an issue while using it: when I select the Cropping mode (i.e., when it is "checked"), an error often occurs. A screenshot of the error is attached. It seems that the issue might be related to the algorithm's inability to handle blank images within comic files.
> 
> To be honest, I’m not very familiar with the technical aspects, so I’ve been testing things out bit by bit. Initially, I suspected that the problem was due to the format conversion software I was using, so I tried several different ones, but the error persisted. Then, I thought it might be related to the PDF format, so I converted it to a folder containing image files and tested again, but the issue remained. Eventually, I discovered that the problem occurs when there are completely blank images within the comic files.
> 
> I further tested and found that the error only happens when the Cropping mode is checked. When it’s set to "indeterminate" or when cropping is not used, everything works fine. Additionally, using the original cropping algorithm version of KCC does not have this issue.


Thabk you for the heads up, it seems like u did a nice investigation. 

It could be that I overlooked an edge-case of blank images. 

I'll confirm it and see what's going on.

**Comment by keruiter** [comment]
> > tmp3EFE
> > tmp14F4
> > image
> > Hi, thank you for providing such an amazing algorithm! However, I encountered an issue while using it: when I select the Cropping mode (i.e., when it is "checked"), an error often occurs. A screenshot of the error is attached. It seems that the issue might be related to the algorithm's inability to handle blank images within comic files.
> > To be honest, I’m not very familiar with the technical aspects, so I’ve been testing things out bit by bit. Initially, I suspected that the problem was due to the format conversion software I was using, so I tried several different ones, but the error persisted. Then, I thought it might be related to the PDF format, so I converted it to a folder containing image files and tested again, but the issue remained. Eventually, I discovered that the problem occurs when there are completely blank images within the comic files.
> > I further tested and found that the error only happens when the Cropping mode is checked. When it’s set to "indeterminate" or when cropping is not used, everything works fine. Additionally, using the original cropping algorithm version of KCC does not have this issue.
> 
> Thank you for the heads up, it seems like u did a nice investigation.
> 
> It could be that I overlooked an edge-case of blank images.
> 
> I'll confirm it and see what's going on.

Thanks for the quick response! Looking forward to your solution~

**Comment by neyney10** [comment]
@axu2 It seems github "sync fork" button made the pull request close automatically, unintentionally on my behalf.

I was making final changes to the commit and was about to upload it.

What should I do? Is there a way to reopen this one or should I create a new PR?

**Comment by neyney10** [comment]
For the update:
1. Replaced the crop margins method with a dumber version of the crop page number algorithm. Frankly, it is quite similar to what existed until now in terms of the idea behind it.
2. Fixed the issue of blank images - as mentioned by @keruiter.
3. Removed the "getBoundingBox" method - Please notify me if this is problematic, I've only seen it used in the crop margins and page number methods, it seems to be limiting the minimum and maximum crop. If such limits are needed let me know.

**Comment by keruiter** [comment]
Hello, thank you so much for the timely update! I was really excited to try it out, but my technical skills are not great, and the process of downloading and packaging it into an executable file was almost too much for me, haha. Thankfully, I managed to get it running in the end.

I downloaded the KCC project directly from your repositories page, and since the update log shows it was updated just a few hours ago, I assume there shouldn’t be any issues with that. All subsequent tests are based on this version.

1. At the beginning of the test, I encountered an issue with an error message that popped up as follows:

   ```
   One of workers crashed. Cause: name 'left' is not defined
   Traceback:
   File "kindlecomicconverter\comic2ebook.py", line 609, in imgFileProcessing
   File "kindlecomicconverter\image.py", line 353, in cropPageNumber
   File "kindlecomicconverter\page_number_crop_alg.py", line 64, in get_bbox_crop_margin_page_number
   ```

   Unfortunately, I forgot to take a screenshot. Since my programming skills are limited, I used OCR to extract the text and consulted GPT for help. Based on the feedback, it seems that in the `get_bbox_crop_margin_page_number` function, variables like `left` and `bot_y_pos` might not have initial values. I asked GPT to assist me, and it suggested adding the following code:
image

I’m not sure if this issue was due to downloading the wrong version or if something went wrong during the packaging process. However, after adding the code as GPT suggested, everything worked fine, so I continued testing.

2. Next, I tested whether cropping an empty image would still crash. I placed a few images that needed page number cropping along with a blank image in an empty folder. Everything worked perfectly! I then tested with cropping power set to 2 and 3. The results were as expected, and everything worked well until I tested a complete PDF comic file, which gave me confusing results.

   In terms of cropping accuracy, with the same cropping power of 2, the results for images in a directory (`dir`) format were much better than those in a PDF format. The cropping for PDFs was less satisfactory, and I selected a few examples to illustrate this.

   Below are the original, unedited files for both `dir` and `pdf` formats:

image
image

   And here are the results with cropping power = 2, using the "crop margins and page number" method:

image
image
Although the images in the `dir` format have been partially cropped (due to settings I used with another conversion tool), I don’t think this should affect the page number cropping. However, the results show that the PDF’s cropping effect seems similar to the original algorithm, with many page numbers left uncropped, which is disappointing.

3. To determine if this was due to the update, I tested using the previous version of KCC (6.0) with the improved cropping algorithm, using the same cropping power = 2. The results were not only normal but also had much better accuracy and cropping effects:
image
​	It even performed better than version 6.2 when the cropping power = 3:

image

image

​	I’m unsure if this issue is caused by the "fix blank image cropping" change or the "Removed the getBoundingBox method" change. In any case, for the same PDF file, the previous version produced better results despite not being able to handle blank images.

​	Honestly, as a non-expert, I’m quite confused about the testing. I don’t know if this behavior is expected, or if the update intentionally weakened the "strength" of the cropping. However, it’s a bit of a pity that the result is not as good as before. Of course, my testing conditions are not rigorous, and I didn’t test many scenarios,  it could also be that I downloaded the wrong version or made a mistake when packaging it into an exe (this process was really tough for a novice like me, haha). If possible, I hope future updates could include a pre-compiled executable. 

Due to time constraints, this is all I could do. I hope it helps with future updates.

**Comment by keruiter** [comment]
> Hello, thank you so much for the timely update! I was really excited to try it out, but my technical skills are not great, and the process of downloading and packaging it into an executable file was almost too much for me, haha. Thankfully, I managed to get it running in the end.
> 
> I downloaded the KCC project directly from your repositories page, and since the update log shows it was updated just a few hours ago, I assume there shouldn’t be any issues with that. All subsequent tests are based on this version.
> 
> 1. At the beginning of the test, I encountered an issue with an error message that popped up as follows:
>    ```
>    One of workers crashed. Cause: name 'left' is not defined
>    Traceback:
>    File "kindlecomicconverter\comic2ebook.py", line 609, in imgFileProcessing
>    File "kindlecomicconverter\image.py", line 353, in cropPageNumber
>    File "kindlecomicconverter\page_number_crop_alg.py", line 64, in get_bbox_crop_margin_page_number
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    Unfortunately, I forgot to take a screenshot. Since my programming skills are limited, I used OCR to extract the text and consulted GPT for help. Based on the feedback, it seems that in the `get_bbox_crop_margin_page_number` function, variables like `left` and `bot_y_pos` might not have initial values. I asked GPT to assist me, and it suggested adding the following code:
>    image
> 
> I’m not sure if this issue was due to downloading the wrong version or if something went wrong during the packaging process. However, after adding the code as GPT suggested, everything worked fine, so I continued testing.
> 
> 2. Next, I tested whether cropping an empty image would still crash. I placed a few images that needed page number cropping along with a blank image in an empty folder. Everything worked perfectly! I then tested with cropping power set to 2 and 3. The results were as expected, and everything worked well until I tested a complete PDF comic file, which gave me confusing results.
>    In terms of cropping accuracy, with the same cropping power of 2, the results for images in a directory (`dir`) format were much better than those in a PDF format. The cropping for PDFs was less satisfactory, and I selected a few examples to illustrate this.
>    Below are the original, unedited files for both `dir` and `pdf` formats:
> 
> image image
> 
> And here are the results with cropping power = 2, using the "crop margins and page number" method:
> 
> image image Although the images in the `dir` format have been partially cropped (due to settings I used with another conversion tool), I don’t think this should affect the page number cropping. However, the results show that the PDF’s cropping effect seems similar to the original algorithm, with many page numbers left uncropped, which is disappointing.
> 
> 3. To determine if this was due to the update, I tested using the previous version of KCC (6.0) with the improved cropping algorithm, using the same cropping power = 2. The results were not only normal but also had much better accuracy and cropping effects:
>    image
>    ​	It even performed better than version 6.2 when the cropping power = 3:
> 
> image
> 
> image
> 
> ​ I’m unsure if this issue is caused by the "fix blank image cropping" change or the "Removed the getBoundingBox method" change. In any case, for the same PDF file, the previous version produced better results despite not being able to handle blank images.
> 
> ​ Honestly, as a non-expert, I’m quite confused about the testing. I don’t know if this behavior is expected, or if the update intentionally weakened the "strength" of the cropping. However, it’s a bit of a pity that the result is not as good as before. Of course, my testing conditions are not rigorous, and I didn’t test many scenarios, it could also be that I downloaded the wrong version or made a mistake when packaging it into an exe (this process was really tough for a novice like me, haha). If possible, I hope future updates could include a pre-compiled executable.
> 
> Due to time constraints, this is all I could do. I hope it helps with future updates.

Sorry to bother you, I just noticed that you modified some code, and after applying your changes, everything is working fine now…… The issue with the reduced cropping effectiveness was likely due to me blindly following the code suggested by GPT. 😅 I hope this didn’t cause you any trouble!

**Comment by neyney10** [comment]
>     1. At the beginning of the test, I encountered an issue with an error message that popped up as follows:
>        ```
>        One of workers crashed. Cause: name 'left' is not defined
>        Traceback:
>        File "kindlecomicconverter\comic2ebook.py", line 609, in imgFileProcessing
>        File "kindlecomicconverter\image.py", line 353, in cropPageNumber
>        File "kindlecomicconverter\page_number_crop_alg.py", line 64, in get_bbox_crop_margin_page_number
>        ```


Yes, this is a mistake on my part. I'm working on the algorithm in a different environment and when I go to update the KCC fork I need to copy and paste the new changes.
Apparently, I've missed a line in my copy & paste process.

The Line is:
`left, top_y_pos, right, bot_y_pos = bw_bbox` 


>     2. Next, I tested whether cropping an empty image would still crash. I placed a few images that needed page number cropping along with a blank image in an empty folder. Everything worked perfectly! I then tested with cropping power set to 2 and 3. The results were as expected, and everything worked well until I tested a complete PDF comic file, which gave me confusing results.
>        In terms of cropping accuracy, with the same cropping power of 2, the results for images in a directory (`dir`) format were much better than those in a PDF format. The cropping for PDFs was less satisfactory, and I selected a few examples to illustrate this.
>        Below are the original, unedited files for both `dir` and `pdf` formats:
> 
>  [... image ...]
> 
> And here are the results with cropping power = 2, using the "crop margins and page number" method:
> 
> [... image ...]
> 
>     3. To determine if this was due to the update, I tested using the previous version of KCC (6.0) with the improved cropping algorithm, using the same cropping power = 2. The results were not only normal but also had much better accuracy and cropping effects:
> [... image ...]
> It even performed better than version 6.2 when the cropping power = 3:
> 
> 
>  [... image ...]
> 
>  [... image ...]
> 
> ​ I’m unsure if this issue is caused by the "fix blank image cropping" change or the "Removed the getBoundingBox method" change. In any case, for the same PDF file, the previous version produced better results despite not being able to handle blank images.
> 
> ​ Honestly, as a non-expert, I’m quite confused about the testing. I don’t know if this behavior is expected, or if the update intentionally weakened the "strength" of the cropping. However, it’s a bit of a pity that the result is not as good as before. Of course, my testing conditions are not rigorous, and I didn’t test many scenarios, it could also be that I downloaded the wrong version or made a mistake when packaging it into an exe (this process was really tough for a novice like me, haha). If possible, I hope future updates could include a pre-compiled executable.
> 
> Due to time constraints, this is all I could do. I hope it helps with future updates.

I'm unsure what caused this, there are no radical changes between 6.0 and 6.2 that should affect the cropping.

However, be advised that currently there is an issue with the algorithm that higher power levels can cause the method to miss the page number or crop it partially. But since you say that there are differences even with the same power level = 2,

Regarding PDF - I haven't tried PDF files, I always assumed it should work similarly as my algorithm processes images and does not care about the source file (directory, zip, cbr, PDF).

@keruiter  **Can you upload an example PDF file for me to test on?**

In order to make it easier for you, I've built the latest version and it can be downloaded here
https://github.com/neyney10/kcc/releases/tag/v6.2.0-crop-algo

**Comment by keruiter** [comment]
> > ```
> > 1. At the beginning of the test, I encountered an issue with an error message that popped up as follows:
> >    ```
> >    One of workers crashed. Cause: name 'left' is not defined
> >    Traceback:
> >    File "kindlecomicconverter\comic2ebook.py", line 609, in imgFileProcessing
> >    File "kindlecomicconverter\image.py", line 353, in cropPageNumber
> >    File "kindlecomicconverter\page_number_crop_alg.py", line 64, in get_bbox_crop_margin_page_number
> >    ```
> > ```
> 
> 是的，这是我的错误。我正在不同的环境中研究算法，当我去更新 KCC 分叉时，我需要复制和粘贴新的更改。显然，我在复制和粘贴过程中漏掉了一行。
> 
> Line 是： `left, top_y_pos, right, bot_y_pos = bw_bbox`
> 
> > ```
> > 2. Next, I tested whether cropping an empty image would still crash. I placed a few images that needed page number cropping along with a blank image in an empty folder. Everything worked perfectly! I then tested with cropping power set to 2 and 3. The results were as expected, and everything worked well until I tested a complete PDF comic file, which gave me confusing results.
> >    In terms of cropping accuracy, with the same cropping power of 2, the results for images in a directory (`dir`) format were much better than those in a PDF format. The cropping for PDFs was less satisfactory, and I selected a few examples to illustrate this.
> >    Below are the original, unedited files for both `dir` and `pdf` formats:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [...图片 ...]
> > 以下是使用 “crop margins and page number” 方法的裁剪功率 = 2 的结果：
> > [...图片 ...]
> > ```
> > 3. To determine if this was due to the update, I tested using the previous version of KCC (6.0) with the improved cropping algorithm, using the same cropping power = 2. The results were not only normal but also had much better accuracy and cropping effects:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [...图片 ...]当裁剪功率 = 3 时，它甚至比 6.2 版表现得更好：
> > [...图片 ...]
> > [...图片 ...]
> > 我不确定此问题是由“修复空白图像裁剪”更改还是“删除了 getBoundingBox 方法”更改引起的。无论如何，对于相同的 PDF 文件，尽管无法处理空白图像，但以前的版本产生了更好的结果。
> > 老实说，作为一个非专家，我对测试感到非常困惑。不知道这种行为是意料之中的，还是更新故意削弱了裁剪的“力度”。不过，结果不如以前，有点可惜。当然，我的测试条件并不严格，也没有测试很多场景，也可能是我下载了错误的版本，或者打包成exe的时候出错了（这个过程对于我这样的新手来说真的很艰难，哈哈）。如果可能的话，我希望未来的更新可以包含预编译的可执行文件。
> > 由于时间有限，我只能做这些了。我希望它对未来的更新有所帮助。
> 
> 我不确定是什么原因造成的，6.0 和 6.2 之间没有根本的变化应该会影响裁剪。
> 
> 但是，请注意，目前算法存在一个问题，即更高的功率级别可能会导致该方法错过页码或部分裁剪页码。但是既然你说即使相同的功率等级 = 2 也存在差异，
> 
> 关于 PDF - 我没有尝试过 PDF 文件，我一直认为它应该类似地工作，因为我的算法处理图像并且不关心源文件（目录、zip、cbr、PDF）。
> 
> **您能否上传一个示例 PDF 文件供我测试？**
> 
> 为了让您更轻松，我构建了最新版本，可以在此处下载 https://github.com/neyney10/kcc/releases/tag/v6.2.0-crop-algo

Sorry to bother you, I just noticed that you modified some code, and after applying your changes, everything is working fine now…… The issue with the reduced cropping effectiveness was likely due to me blindly following the code suggested by GPT😅  I hope this didn’t cause you any trouble.

**Comment by neyney10** [comment]
@axu2 Please review this to see if it is ready for merge.

**Comment by axu2** [comment]
Thanks for the reminder, I will do it very soon.

**Comment by axu2** [comment]
Alright, I'm ready to merge as a tentative 7.0.0 release, because the numpy dependency is a big dependency change. Get ready for more user feedback since this is now in the actual releases tab instead of being linked in the release notes.

Is this alright as the first line in the release notes?


> A new page number crop algorithm has been implemented to optimize vertical screen real estate, please test and provide feedback. It is optimized for power = 1.0


code quality is great, I only have some minor nitpicks about defining functions before you use them and the fact that the margin crop algorithm should be defined first to make reviewing easier. Maybe the page# crop algo should call the margin crop algo to reduce duplicated code/comments.

People in the discord have reported good results with the new algo.

I have merged this for now, but I'll keep looking into it, I wonder if any python or numpy built ins can do what the helper functions are doing?

**Comment by neyney10** [comment]
> Alright, I'm ready to merge as a tentative 7.0.0 release, because the numpy dependency is a big dependency change. Get ready for more user feedback since this is now in the actual releases tab instead of being linked in the release notes.
> 
> Is this alright as the first line in the release notes?
> 
> > A new page number crop algorithm has been implemented to optimize vertical screen real estate, please test and provide feedback. It is optimized for power = 1.0
> 

Ye, it's okay.

> code quality is great, I only have some minor nitpicks about defining functions before you use them and the fact that the margin crop algorithm should be defined first to make reviewing easier. Maybe the page# crop algo should call the margin crop algo to reduce duplicated code/comments.

I guess we can somehow reduce duplicated code by reusing a more open function of the margin cropping algo.

> People in the discord have reported good results with the new algo.
> 
> I have merged this for now, but I'll keep looking into it, I wonder if any python or numpy built ins can do what the helper functions are doing? Since kcc has no unit tests, always unsure if we miss a corner case.

During the development of the algorithm, I've created a small test system. It applies the algorithm on dozens of images and checks if it cropped them okay and matches the expected boxes.

I've used numpy in the helper functions... I don't know if there is are better fit functions that encompass more of the logic contained in the helper functions... But I agree, I'm worried of corner cases as well.

> And armv7 now takes forever to build due to numpy source build...
> 
> image

Oh. Why is that? Is it because NumPy package isnt optimized for arm? Maybe NumPy v2+ is more optimized?

**Comment by axu2** [comment]
Lots of packages including numpy don't have armv7 wheels. don't worry about it, just a curious observation. armv7 is typically just older raspberry pi.

**Pull request merged**
