### PR TITLE
Add Appimage link for Linux binary

### PR DESCRIPTION
**Pull request by CrownCrafter**
x86_64 Appimage support for kcc.
Solves #307.

### CODE REVIEW

**Comment by CrownCrafter** [comment]
I will add appimages for other architectures when merged(rpi appimage).

**Comment by darodi** [comment]
Could you provide a pull request that generates an AppImage as part of the project’s build pipeline?
That would be better than just a fixed AppImage that needs to be changed on every source change.

**Comment by CrownCrafter** [comment]
So sorry to sound dumb, but I don't know how to edit the build pipeline?

**Comment by darodi** [comment]
If you can't edit/create the pipeline, can you provide the yml recipe you used to create the AppImage?
So I could include it in an example pipeline for you.
Thanks in advance.

**Pull request closed without merging**
