### PR TITLE
fix mac cover upload when frozen by removing plist

### LINKED ISSUE #436: MacOS Monterey v12.6: “Kindle Comic Converter” cannot be opened because the developer cannot be verified.
When I try to open the KCC App on my MacBook I get the following message:
Screenshot 2022-09-16 at 17 15 29

“Kindle Comic Converter” cannot be opened because the developer cannot be verified.
macOS cannot verify that this app is free from malware.

### LINKED ISSUE #482: MOBI generation stuck if Kindle is mounted to macOS
Using **v5.6.1**, if I attempt to create a **MOBI** file when my _Kindle Paperwhite (10th Gen)_ is mounted in macOS, KCC will indefinitely stall out following the `Processing MOBI files...Done!` step.

If I unmount the device, it works normally.

(I'm on **macOS 13.2.1**, if that makes any difference.)

### PR DESCRIPTION
**Pull request by axu2**
Fixes #482

Fixes #436 together with #565

To clarify frozen is referring to a pyinstaller built binary

EDIT: Various issues that turned out to be unrelated were deleted.

### CODE REVIEW

**Comment by darodi** [comment]
> Also, do you have a particular reason to not ignore `*.spec` files? I don't see a reason to include them since they are auto-generated by PyInstaller and are included in the standard Python gitignore: https://github.com/github/gitignore/blob/main/Python.gitignore


spec files are used in the build process and had to be adapted from the auto generated ones.

https://github.com/ciromattia/kcc/blob/217f571f3d8b24fca13667de46e59effb926dc44/.github/workflows/package-windows-with-docker.yml#L28-L42

**Comment by darodi** [comment]
> And that plist appears to be unused.

The file is needed by the bundle normally. 

https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPRuntimeConfig/Articles/ConfigFiles.html#//apple_ref/doc/uid/20002091-CJBJIEDH
>An information property list file is a structured text file that contains essential configuration information for a bundled executable.

Are you using a bundled binary?
Here you said you are not.
> I've never tried running the binary.
_Originally posted by @axu2 in https://github.com/ciromattia/kcc/issues/482#issuecomment-1575099852_
            
removing the included binaries will complicate things for those using them with older mac os architectures.

**disclaimer**: I don't own an Apple computer currently and can't test this PR right now.
A good soul will have to test/review this.
(Or I need to annoy my mother-in-law and borrow hers)

**Comment by axu2** [comment]
OK, I thought multiple issues were related, but turns out they aren't, so I'll be editing this PR to only focus on the plist.

PyInstaller provides a plist file like in my first post here:

image

If we attempt to copy in our own plist we get the permission issue. I have no clue why, but I don't think our plist is doing anything functional.

**Comment by axu2** [comment]
Superseded by https://github.com/ciromattia/kcc/pull/566 due to merge conflicts

**Pull request closed without merging**
